# Generated by Django 3.2.6 on 2023-06-06 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_con', models.FloatField(blank=True, verbose_name='Ingreso Conciliacion')),
                ('ingcop_con', models.FloatField(blank=True, verbose_name='Ingreso Copias Conciliacion')),
                ('toting_con', models.FloatField(blank=True, verbose_name='Total Ingreso Copias')),
                ('egre_con', models.FloatField(blank=True, verbose_name='Egreso Copias')),
            ],
            options={
                'verbose_name': 'CajaConciliacion',
                'verbose_name_plural': 'CajaConciliaciones',
                'db_table': 'JJ_CAJA_CONCILIACION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_cat', models.CharField(max_length=40, verbose_name='Descripcion Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
                'db_table': 'JJ_CATEGORIA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'JJ_CLIENTE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_conf', models.CharField(max_length=4, verbose_name='Año Configuracion')),
                ('num_sol', models.IntegerField(verbose_name='Número de Solicitud')),
                ('num_act', models.IntegerField(verbose_name='Número de Acta')),
                ('est_conf', models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=10, verbose_name='Estado Configuracion')),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'JJ_CONFIGURACION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_esp', models.CharField(max_length=50, verbose_name='Especificacion')),
                ('cos_esp', models.FloatField(verbose_name='Costo Conciliacion')),
            ],
            options={
                'verbose_name': 'Especificacion',
                'verbose_name_plural': 'Especificaciones',
                'db_table': 'JJ_ESPECIFICACION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_exp', models.CharField(max_length=10, verbose_name='Numero de Expediente')),
                ('fec_exp', models.DateTimeField(verbose_name='Fecha Expediente')),
                ('hor_exp', models.TimeField(verbose_name='Hora Expediente')),
                ('proini_exp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Procedimiento Iniciado')),
                ('esttra_exp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Tramite')),
                ('estact_exp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Concluido/No Concluido Con Acta')),
                ('audact_exp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Audicion Unica')),
                ('numfol_exp', models.IntegerField(verbose_name='Numero de Folios')),
                ('confin_exp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Finalizado o No Finalizado')),
                ('carp_exp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Carpeta Expediente')),
                ('subcarpdf_exp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Carpeta Expediente')),
                ('inv_exp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Invitacion Expediente')),
                ('tipcon_exp', models.CharField(choices=[('ma', 'Mismo Acto'), ('ci', 'Con Invitacion')], default='ma', max_length=20, verbose_name='Tipo de Conciliacion')),
                ('id_conf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.configuracion', verbose_name='Id Configuracion')),
                ('id_esp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.especificacion', verbose_name='Id Especificacion')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'db_table': 'JJ_EXPEDIENTE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_inf', models.CharField(max_length=40, verbose_name='Tipo de Informe')),
                ('fec_inf', models.DateTimeField(verbose_name='Fecha Informe')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'db_table': 'JJ_INFORME',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacpag_con', models.FloatField(blank=True, verbose_name='Pago Pactado Conciliacion')),
                ('pagpacade_con', models.FloatField(blank=True, verbose_name='Pago Pactado Adelantado Conciliacion')),
                ('toting_con', models.FloatField(blank=True, verbose_name='Total Ingreso Copias')),
                ('idcaj_con', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cajaconciliacion', verbose_name='id Persona')),
            ],
            options={
                'verbose_name': 'CajaConciliacion',
                'verbose_name_plural': 'CajaConciliaciones',
                'db_table': 'JJ_INGRESO_CONCILIACION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoCopias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monpag_cop', models.FloatField(blank=True, verbose_name='Monto Pago Copias')),
                ('idcaj_con', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cajaconciliacion', verbose_name='id Caja Conciliacion')),
            ],
            options={
                'verbose_name': 'IngresoCopia',
                'verbose_name_plural': 'IngresoCopias',
                'db_table': 'JJ_INGRESO_COPIAS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_mat', models.CharField(max_length=50, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'JJ_MATERIA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_per', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apepat_per', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('apemat_per', models.CharField(max_length=255, verbose_name='Apellido Materno')),
                ('numdoc_per', models.IntegerField(unique=True, verbose_name='DNI')),
                ('eda_per', models.IntegerField(verbose_name='Edad')),
                ('sex_per', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=10, verbose_name='Sexo')),
                ('dir_per', models.CharField(max_length=200, verbose_name='Direccion')),
                ('numcel_per', models.CharField(blank=True, max_length=9, null=True, verbose_name='Numero de Celular')),
                ('ema_per', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'JJ_PERSONA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecdoc_sol', models.DateTimeField(verbose_name='Fecha de Solicitud')),
                ('hecdoc_sol', models.CharField(max_length=5000, verbose_name='Hechos de Solicitud')),
                ('pretsoldoc_sol', models.CharField(max_length=5000, verbose_name='Pretension de Solicitud')),
                ('pretactdoc_sol', models.CharField(max_length=5000, verbose_name='Pretension de Acta')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'JJ_SOLICITUD',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
                ('id_per', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.persona', verbose_name='Id Persona')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'db_table': 'JJ_SOLICITANTE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_soc', models.CharField(max_length=40, verbose_name='Codigo Socio')),
                ('id_per', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.persona', verbose_name='Id Persona')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'JJ_SOCIO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pro', models.CharField(max_length=40, verbose_name='Nombre Producto')),
                ('cant_pro', models.CharField(max_length=3, verbose_name='Cantidad Producto')),
                ('tip_pro', models.CharField(max_length=40, verbose_name='Tipo Producto')),
                ('mon_pro', models.FloatField(blank=True, verbose_name='Total Producto')),
                ('fec_pro', models.DateTimeField(verbose_name='Fecha Prodcuto')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.categoria', verbose_name='id Categoria')),
                ('idcaj_con', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cajaconciliacion', verbose_name='id Caja Conciliacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'JJ_PRODUCTO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_pro', models.CharField(max_length=50, verbose_name='Procedimiento')),
                ('id_mat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.materia', verbose_name='Id Materia')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'db_table': 'JJ_PROCEDIMIENTO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_par', models.IntegerField(verbose_name='Numero Parcial')),
                ('id_inf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.informe', verbose_name='Id Informe')),
            ],
            options={
                'verbose_name': 'Parcial',
                'verbose_name_plural': 'Parciales',
                'db_table': 'JJ_PARCIAL',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
                ('id_per', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.persona', verbose_name='id Persona')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'db_table': 'JJ_INVITADO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_invi', models.CharField(max_length=50, verbose_name='Tipo de Invitacion')),
                ('fec_invi', models.DateTimeField(verbose_name='Fecha de Invitacion')),
                ('hor_invi', models.TimeField(verbose_name='Hora de Invitacion')),
                ('esc_invi', models.CharField(max_length=100, verbose_name='Escaneado de Invitacion')),
                ('id_inv', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.invitado', verbose_name='Id Invitado')),
            ],
            options={
                'verbose_name': 'Invitacion',
                'verbose_name_plural': 'Invitaciones',
                'db_table': 'JJ_INVITACION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoCopiasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancop_det', models.IntegerField(verbose_name='Cantidad Copia Detalle')),
                ('moncop_det', models.FloatField(blank=True, verbose_name='Monto Copia Detalle')),
                ('feccop_det', models.DateTimeField(verbose_name='Fecha Copia Detalle')),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cliente', verbose_name='id Cliente')),
                ('iding_cop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.ingresocopias', verbose_name='id Ingreso Copias')),
            ],
            options={
                'verbose_name': 'IngresoCopiasDetalle',
                'verbose_name_plural': 'IngresoCopiasDetalles',
                'db_table': 'JJ_INGRESO_COPIAS_DETALLE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoConciliacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monadedet_con', models.FloatField(blank=True, verbose_name='Monto Adelantado Detalle Conciliacion')),
                ('fecmondet_con', models.DateTimeField(verbose_name='Fecha Monto Detalle Conciliacion')),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cliente', verbose_name='id Ingreso Conciliacion')),
                ('idpag_con', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.ingresoconciliacion', verbose_name='id Ingreso Conciliacion')),
            ],
            options={
                'verbose_name': 'IngresoConciliacionDetalle',
                'verbose_name_plural': 'IngresoConciliacionDetalles',
                'db_table': 'JJ_INGRESO_CONCILIACION_DETALLE',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='especificacion',
            name='id_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.procedimiento', verbose_name='Id Procedimiento'),
        ),
        migrations.CreateModel(
            name='EgresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monegre_det', models.FloatField(blank=True, verbose_name='Monto Egreso Detalle')),
                ('fecegre_det', models.DateTimeField(verbose_name='Fecha Egreso Detalle')),
                ('tipinv_con', models.CharField(max_length=50, verbose_name='Tipo Invitacion Conciliacion')),
                ('totegre_con', models.FloatField(blank=True, verbose_name='Total Ingreso Conciliacion')),
                ('idcaj_con', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cajaconciliacion', verbose_name='id Caja Conciliacion')),
            ],
            options={
                'verbose_name': 'EgresoDetalle',
                'verbose_name_plural': 'EgresoDetalles',
                'db_table': 'JJ_EGRESO_DETALLE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_doc', models.CharField(max_length=20, verbose_name='Tipo de Documento')),
                ('arcesc_doc', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'JJ_DOCUMENTO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConstanciaSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feccon_sol', models.DateTimeField(verbose_name='Fecha Constancia Solicitante')),
                ('horcon_sol', models.TimeField(verbose_name='Hora Constancia Solicitante')),
                ('esccon_sol', models.CharField(max_length=300, verbose_name='Escaneado Constancia Solicitante')),
                ('id_sol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.solicitante', verbose_name='Id Solicitante')),
            ],
            options={
                'verbose_name': 'ConstanciaSolicitante',
                'verbose_name_plural': 'ConstanciaSolicitantes',
                'db_table': 'JJ_CONSTANCIASOLICITANTE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConstanciaInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feccon_inv', models.DateTimeField(verbose_name='Fecha Constancia Invitado')),
                ('horcon_inv', models.TimeField(verbose_name='Hora Constancia Invitado')),
                ('esccon_inv', models.CharField(max_length=300, verbose_name='Escaneado Constancia Invitado')),
                ('id_inv', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.invitado', verbose_name='Id Invitado')),
            ],
            options={
                'verbose_name': 'ConstanciaInvitado',
                'verbose_name_plural': 'ConstanciasInvitados',
                'db_table': 'JJ_CONSTANCIAINVITADO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Conciliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_doc', models.TimeField(verbose_name='Hora Documento')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
            ],
            options={
                'verbose_name': 'Conciliador',
                'verbose_name_plural': 'Conciliadores',
                'db_table': 'JJ_CONCILIADOR',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.persona', verbose_name='Id Persona'),
        ),
        migrations.AddField(
            model_name='cajaconciliacion',
            name='id_exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='id Expediente'),
        ),
        migrations.AddField(
            model_name='cajaconciliacion',
            name='id_soc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.socio', verbose_name='id Socio'),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit_age', models.CharField(max_length=150, verbose_name='Titulo de Agenda')),
                ('des_age', models.CharField(max_length=500, verbose_name='Descripcionde  Agenda')),
                ('url_age', models.CharField(max_length=150, verbose_name='URL de Agenda')),
                ('clas_age', models.CharField(max_length=45, verbose_name='Clase de Agenda')),
                ('ini_age', models.CharField(max_length=15, verbose_name='Inicio de Agenda')),
                ('fin_age', models.CharField(max_length=15, verbose_name='Fin de Agenda')),
                ('ininor_age', models.CharField(max_length=50, verbose_name='Inicio Normal de Agente')),
                ('finnor_age', models.CharField(max_length=50, verbose_name='Fin Normal de Agente')),
                ('fecaud_age', models.DateTimeField(verbose_name='Fecha Audiencia Agenda')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'db_table': 'JJ_AGENDA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_act', models.IntegerField(blank=True, null=True, verbose_name='Numero de Acta')),
                ('id_inf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.informe', verbose_name='Id Informe')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'db_table': 'JJ_ACTA',
                'ordering': ['id'],
            },
        ),
    ]
