# Generated by Django 3.2.6 on 2023-07-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fec_exp',
            field=models.DateField(verbose_name='Fecha Expediente'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='eda_per',
            field=models.CharField(max_length=2, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numdoc_per',
            field=models.CharField(max_length=8, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='cod_soc',
            field=models.CharField(max_length=40, unique=True, verbose_name='Codigo Socio'),
        ),
    ]
