# Generated by Django 3.2.6 on 2023-08-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0002_auto_20230703_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='num_sol',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='num_exp',
            field=models.IntegerField(null=True, verbose_name='Número de Expediente'),
        ),
    ]
