# Generated by Django 3.2.6 on 2023-08-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0004_alter_documento_tip_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecdoc_sol',
            field=models.DateField(null=True, verbose_name='Fecha de Solicitud'),
        ),
    ]
