# Generated by Django 3.2.6 on 2023-08-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0005_alter_solicitud_fecdoc_sol'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliador',
            name='hor_doc',
            field=models.TimeField(null=True, verbose_name='Hora Documento'),
        ),
        migrations.AlterField(
            model_name='conciliador',
            name='fec_doc',
            field=models.DateField(null=True, verbose_name='Fecha Documento'),
        ),
    ]
