# Generated by Django 3.2.6 on 2023-09-21 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0007_auto_20230920_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
