# Generated by Django 3.2.6 on 2023-09-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ccjj', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_conf', models.CharField(max_length=4, verbose_name='Año Configuracion')),
                ('num_exp', models.IntegerField(null=True, verbose_name='Número de Expediente')),
                ('num_act', models.IntegerField(verbose_name='Número de Acta')),
                ('est_conf', models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=10, verbose_name='Estado Configuracion')),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'JJ_CONFIGURACION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_mat', models.CharField(max_length=50, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'JJ_MATERIA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_per', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apepat_per', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('apemat_per', models.CharField(max_length=255, verbose_name='Apellido Materno')),
                ('numdoc_per', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('eda_per', models.CharField(max_length=2, verbose_name='Edad')),
                ('sex_per', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=10, verbose_name='Sexo')),
                ('dir_per', models.CharField(max_length=200, verbose_name='Direccion')),
                ('numcel_per', models.CharField(blank=True, max_length=9, null=True, verbose_name='Numero de Celular')),
                ('ema_per', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'JJ_PERSONA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_soc', models.CharField(max_length=40, unique=True, verbose_name='Codigo Socio')),
                ('id_per', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.persona', verbose_name='Id Persona')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'JJ_SOCIO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_pro', models.CharField(max_length=50, verbose_name='Procedimiento')),
                ('id_mat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.materia', verbose_name='Id Materia')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'db_table': 'JJ_PROCEDIMIENTO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_esp', models.CharField(max_length=50, verbose_name='Especificacion')),
                ('cos_esp', models.FloatField(verbose_name='Costo Conciliacion')),
                ('id_pro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.procedimiento', verbose_name='Id Procedimiento')),
            ],
            options={
                'verbose_name': 'Especificacion',
                'verbose_name_plural': 'Especificaciones',
                'db_table': 'JJ_ESPECIFICACION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_per', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.persona', verbose_name='Id Persona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'JJ_CLIENTE',
                'ordering': ['id'],
            },
        ),
    ]
