# Generated by Django 3.2.6 on 2023-09-21 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccjj', '0009_cliente_configuracion_especificacion_materia_persona_procedimiento_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_exp', models.CharField(max_length=10, verbose_name='Numero de Expediente')),
                ('fec_exp', models.DateField(verbose_name='Fecha Expediente')),
                ('hor_exp', models.TimeField(verbose_name='Hora Expediente')),
                ('proini_exp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Procedimiento Iniciado')),
                ('esttra_exp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Tramite')),
                ('estact_exp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Concluido/No Concluido Con Acta')),
                ('audact_exp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Audicion Unica')),
                ('numfol_exp', models.IntegerField(verbose_name='Numero de Folios')),
                ('confin_exp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Finalizado o No Finalizado')),
                ('carp_exp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Carpeta Expediente')),
                ('subcarpdf_exp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Carpeta Expediente')),
                ('inv_exp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Invitacion Expediente')),
                ('tipcon_exp', models.CharField(choices=[('ma', 'Mismo Acto'), ('ci', 'Con Invitacion')], default='ma', max_length=20, verbose_name='Tipo de Conciliacion')),
                ('id_conf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.configuracion', verbose_name='Id Configuracion')),
                ('id_esp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.especificacion', verbose_name='Id Especificacion')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'db_table': 'JJ_EXPEDIENTE',
                'ordering': ['id'],
            },
        ),
    ]
