# Generated by Django 3.2.6 on 2023-09-21 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0010_expediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_con', models.FloatField(blank=True, verbose_name='Ingreso Conciliacion')),
                ('ingcop_con', models.FloatField(blank=True, verbose_name='Ingreso Copias Conciliacion')),
                ('toting_con', models.FloatField(blank=True, verbose_name='Total Ingreso Copias')),
                ('egre_con', models.FloatField(blank=True, verbose_name='Egreso Copias')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='id Expediente')),
                ('id_soc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.socio', verbose_name='id Socio')),
            ],
            options={
                'verbose_name': 'CajaConciliacion',
                'verbose_name_plural': 'CajaConciliaciones',
                'db_table': 'JJ_CAJA_CONCILIACION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_cat', models.CharField(max_length=40, verbose_name='Descripcion Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
                'db_table': 'JJ_CATEGORIA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_inf', models.CharField(max_length=40, verbose_name='Tipo de Informe')),
                ('fec_inf', models.DateTimeField(verbose_name='Fecha Informe')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'db_table': 'JJ_INFORME',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacpag_con', models.FloatField(blank=True, verbose_name='Pago Pactado Conciliacion')),
                ('pagpacade_con', models.FloatField(blank=True, verbose_name='Pago Pactado Adelantado Conciliacion')),
                ('toting_con', models.FloatField(blank=True, verbose_name='Total Ingreso Copias')),
                ('idcaj_con', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cajaconciliacion', verbose_name='id Persona')),
            ],
            options={
                'verbose_name': 'CajaConciliacion',
                'verbose_name_plural': 'CajaConciliaciones',
                'db_table': 'JJ_INGRESO_CONCILIACION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoCopias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monpag_cop', models.FloatField(blank=True, verbose_name='Monto Pago Copias')),
                ('idcaj_con', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cajaconciliacion', verbose_name='id Caja Conciliacion')),
            ],
            options={
                'verbose_name': 'IngresoCopia',
                'verbose_name_plural': 'IngresoCopias',
                'db_table': 'JJ_INGRESO_COPIAS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecdoc_sol', models.DateField(null=True, verbose_name='Fecha de Solicitud')),
                ('hecdoc_sol', models.CharField(max_length=5000, verbose_name='Hechos de Solicitud')),
                ('pretsoldoc_sol', models.CharField(max_length=5000, verbose_name='Pretension de Solicitud')),
                ('pretactdoc_sol', models.CharField(max_length=5000, verbose_name='Pretension de Acta')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'JJ_SOLICITUD',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
                ('id_per', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.persona', verbose_name='Id Persona')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'db_table': 'JJ_SOLICITANTE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pro', models.CharField(max_length=40, verbose_name='Nombre Producto')),
                ('cant_pro', models.CharField(max_length=3, verbose_name='Cantidad Producto')),
                ('tip_pro', models.CharField(max_length=40, verbose_name='Tipo Producto')),
                ('mon_pro', models.FloatField(blank=True, verbose_name='Total Producto')),
                ('fec_pro', models.DateTimeField(verbose_name='Fecha Prodcuto')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.categoria', verbose_name='id Categoria')),
                ('idcaj_con', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cajaconciliacion', verbose_name='id Caja Conciliacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'JJ_PRODUCTO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_par', models.IntegerField(verbose_name='Numero Parcial')),
                ('id_inf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.informe', verbose_name='Id Informe')),
            ],
            options={
                'verbose_name': 'Parcial',
                'verbose_name_plural': 'Parciales',
                'db_table': 'JJ_PARCIAL',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
                ('id_per', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.persona', verbose_name='id Persona')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'db_table': 'JJ_INVITADO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_invi', models.CharField(max_length=50, verbose_name='Tipo de Invitacion')),
                ('fec_invi', models.DateTimeField(verbose_name='Fecha de Invitacion')),
                ('hor_invi', models.TimeField(verbose_name='Hora de Invitacion')),
                ('esc_invi', models.CharField(max_length=100, verbose_name='Escaneado de Invitacion')),
                ('id_inv', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.invitado', verbose_name='Id Invitado')),
            ],
            options={
                'verbose_name': 'Invitacion',
                'verbose_name_plural': 'Invitaciones',
                'db_table': 'JJ_INVITACION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoCopiasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancop_det', models.IntegerField(verbose_name='Cantidad Copia Detalle')),
                ('moncop_det', models.FloatField(blank=True, verbose_name='Monto Copia Detalle')),
                ('feccop_det', models.DateTimeField(verbose_name='Fecha Copia Detalle')),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cliente', verbose_name='id Cliente')),
                ('iding_cop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.ingresocopias', verbose_name='id Ingreso Copias')),
            ],
            options={
                'verbose_name': 'IngresoCopiasDetalle',
                'verbose_name_plural': 'IngresoCopiasDetalles',
                'db_table': 'JJ_INGRESO_COPIAS_DETALLE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoConciliacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monadedet_con', models.FloatField(blank=True, verbose_name='Monto Adelantado Detalle Conciliacion')),
                ('fecmondet_con', models.DateTimeField(verbose_name='Fecha Monto Detalle Conciliacion')),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cliente', verbose_name='id Ingreso Conciliacion')),
                ('idpag_con', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.ingresoconciliacion', verbose_name='id Ingreso Conciliacion')),
            ],
            options={
                'verbose_name': 'IngresoConciliacionDetalle',
                'verbose_name_plural': 'IngresoConciliacionDetalles',
                'db_table': 'JJ_INGRESO_CONCILIACION_DETALLE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EgresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monegre_det', models.FloatField(blank=True, verbose_name='Monto Egreso Detalle')),
                ('fecegre_det', models.DateTimeField(verbose_name='Fecha Egreso Detalle')),
                ('tipinv_con', models.CharField(max_length=50, verbose_name='Tipo Invitacion Conciliacion')),
                ('totegre_con', models.FloatField(blank=True, verbose_name='Total Ingreso Conciliacion')),
                ('idcaj_con', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cajaconciliacion', verbose_name='id Caja Conciliacion')),
            ],
            options={
                'verbose_name': 'EgresoDetalle',
                'verbose_name_plural': 'EgresoDetalles',
                'db_table': 'JJ_EGRESO_DETALLE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_doc', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('arcesc_doc', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'JJ_DOCUMENTO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConstanciaSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feccon_sol', models.DateTimeField(verbose_name='Fecha Constancia Solicitante')),
                ('horcon_sol', models.TimeField(verbose_name='Hora Constancia Solicitante')),
                ('esccon_sol', models.CharField(max_length=300, verbose_name='Escaneado Constancia Solicitante')),
                ('id_sol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.solicitante', verbose_name='Id Solicitante')),
            ],
            options={
                'verbose_name': 'ConstanciaSolicitante',
                'verbose_name_plural': 'ConstanciaSolicitantes',
                'db_table': 'JJ_CONSTANCIASOLICITANTE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConstanciaInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feccon_inv', models.DateTimeField(verbose_name='Fecha Constancia Invitado')),
                ('horcon_inv', models.TimeField(verbose_name='Hora Constancia Invitado')),
                ('esccon_inv', models.CharField(max_length=300, verbose_name='Escaneado Constancia Invitado')),
                ('id_inv', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.invitado', verbose_name='Id Invitado')),
            ],
            options={
                'verbose_name': 'ConstanciaInvitado',
                'verbose_name_plural': 'ConstanciasInvitados',
                'db_table': 'JJ_CONSTANCIAINVITADO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Conciliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_doc', models.DateField(null=True, verbose_name='Fecha Documento')),
                ('hor_doc', models.TimeField(null=True, verbose_name='Hora Documento')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
            ],
            options={
                'verbose_name': 'Conciliador',
                'verbose_name_plural': 'Conciliadores',
                'db_table': 'JJ_CONCILIADOR',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit_age', models.CharField(max_length=150, verbose_name='Titulo de Agenda')),
                ('des_age', models.CharField(max_length=500, verbose_name='Descripcionde  Agenda')),
                ('url_age', models.CharField(max_length=150, verbose_name='URL de Agenda')),
                ('clas_age', models.CharField(max_length=45, verbose_name='Clase de Agenda')),
                ('ini_age', models.CharField(max_length=15, verbose_name='Inicio de Agenda')),
                ('fin_age', models.CharField(max_length=15, verbose_name='Fin de Agenda')),
                ('ininor_age', models.CharField(max_length=50, verbose_name='Inicio Normal de Agente')),
                ('finnor_age', models.CharField(max_length=50, verbose_name='Fin Normal de Agente')),
                ('fecaud_age', models.DateTimeField(verbose_name='Fecha Audiencia Agenda')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.expediente', verbose_name='Id Expediente')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'db_table': 'JJ_AGENDA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_act', models.IntegerField(blank=True, null=True, verbose_name='Numero de Acta')),
                ('id_inf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.informe', verbose_name='Id Informe')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'db_table': 'JJ_ACTA',
                'ordering': ['id'],
            },
        ),
    ]
