# Generated by Django 3.2.6 on 2023-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0012_ingresoconciliacion_desc_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='estpro_exp',
            field=models.CharField(choices=[('exp', 'Expediente'), ('mat', 'Materia Conciliacion'), ('esq', 'Esquela de Conciliador'), ('caj', 'Caja Conciliacion'), ('inv', 'Invitacion'), ('act', 'acta')], default='exp', max_length=20, null=True, verbose_name='Estado de Proceso de Conciliacion'),
        ),
        migrations.AlterField(
            model_name='cajaconciliacion',
            name='egre_con',
            field=models.FloatField(blank=True, verbose_name='Egreso'),
        ),
        migrations.AlterField(
            model_name='cajaconciliacion',
            name='toting_con',
            field=models.FloatField(blank=True, verbose_name='Total Ingreso'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='tip_inf',
            field=models.CharField(choices=[('at', 'Acuerdo Total'), ('ap', 'Acuerdo Parcial'), ('fa', 'Falta De Acuerdo'), ('is', 'Inasistencia Solicitante'), ('ii', 'Inasistencia Invitado'), ('iap', 'Inasistencia de Ambas Partes'), ('am', 'Acta Motivada'), ('ci', 'Conclusion Con Informe')], default='at', max_length=40, verbose_name='Tipo de Informe'),
        ),
        migrations.AlterField(
            model_name='ingresoconciliacion',
            name='toting_con',
            field=models.FloatField(blank=True, verbose_name='Total Ingreso'),
        ),
    ]
