# Generated by Django 3.2.6 on 2023-10-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0013_auto_20231007_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estpro_exp',
            field=models.CharField(choices=[('exp', 'Expediente'), ('sol', 'Solicitud'), ('mat', 'Materia Conciliacion'), ('esq', 'Esquela de Conciliador'), ('inv', 'Invitacion'), ('caj', 'Caja Conciliacion'), ('act', 'acta')], default='exp', max_length=20, null=True, verbose_name='Estado de Proceso de Conciliacion'),
        ),
    ]
