# Generated by Django 3.2.6 on 2023-10-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0014_alter_expediente_estpro_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresoconciliaciondetalle',
            name='fecmondet_con',
        ),
        migrations.AddField(
            model_name='ingresoconciliaciondetalle',
            name='fecingdet_con',
            field=models.DateField(null=True, verbose_name='Fecha Ingreso Conciliacion Detalle'),
        ),
        migrations.AddField(
            model_name='ingresoconciliaciondetalle',
            name='horingdet_con',
            field=models.TimeField(null=True, verbose_name='Hora Ingreso Conciliacion Detalle'),
        ),
    ]
