# Generated by Django 3.2.6 on 2023-10-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0016_auto_20231017_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='fec_invi',
            field=models.DateField(verbose_name='Fecha de Invitacion'),
        ),
    ]
