# Generated by Django 3.2.6 on 2023-10-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0017_alter_invitacion_fec_invi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='clas_age',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='fecaud_age',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='finnor_age',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='ininor_age',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='des_age',
            field=models.CharField(max_length=500, verbose_name='Descripcion de  Agenda'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fin_age',
            field=models.DateTimeField(max_length=15, verbose_name='Fin de Agenda'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='ini_age',
            field=models.DateTimeField(max_length=15, verbose_name='Inicio de Agenda'),
        ),
    ]
