# Generated by Django 3.2.6 on 2023-10-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0018_auto_20231026_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='fin_age',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='ini_age',
        ),
        migrations.AddField(
            model_name='agenda',
            name='borcolor_age',
            field=models.CharField(max_length=20, null=True, verbose_name='Color Borde'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='fecaud_age',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Agenda'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='foncolor_age',
            field=models.CharField(max_length=20, null=True, verbose_name='Color Fondo'),
        ),
    ]
