# Generated by Django 3.2.6 on 2023-10-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0019_auto_20231026_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estact_exp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concluido/No Concluido Con Acta'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='esttra_exp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Tramite'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='proini_exp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procedimiento Iniciado'),
        ),
    ]
