# Generated by Django 3.2.6 on 2024-03-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0021_alter_documento_arcesc_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='carp_exp',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='subcarpdf_exp',
        ),
    ]
