# Generated by Django 3.2.6 on 2024-03-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0024_auto_20240302_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresocopias',
            name='cancop_cop',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Copias'),
        ),
        migrations.AddField(
            model_name='ingresocopias',
            name='fec_cop',
            field=models.DateField(null=True, verbose_name='Fecha Copias'),
        ),
        migrations.AddField(
            model_name='ingresocopias',
            name='hor_cop',
            field=models.TimeField(null=True, verbose_name='Hora Copias'),
        ),
        migrations.AddField(
            model_name='ingresocopias',
            name='id_cli_cop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ccjj.cliente', verbose_name='id Cliente'),
        ),
        migrations.DeleteModel(
            name='IngresoCopiasDetalle',
        ),
    ]
