# Generated by Django 3.2.6 on 2024-03-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0026_auto_20240303_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='esc_invi',
            field=models.FileField(blank=True, null=True, upload_to='Documentos/%Y/%m/%d/', verbose_name='Invitación Escaneado'),
        ),
    ]
