# Generated by Django 3.2.6 on 2024-03-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0030_auto_20240318_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoconciliacion',
            name='estado_con',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Ingreso Conciliacion'),
        ),
    ]
