# Generated by Django 3.2.6 on 2024-03-25 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0032_auto_20240319_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoconciliaciondetalle',
            name='id_cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ccjj.persona', verbose_name='id Cliente'),
        ),
        migrations.AlterField(
            model_name='ingresocopias',
            name='id_cli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ccjj.persona', verbose_name='id Cliente'),
        ),
    ]
