# Generated by Django 3.2.6 on 2024-03-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0033_auto_20240324_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacion',
            name='des_esp',
            field=models.CharField(max_length=100, verbose_name='Especificacion'),
        ),
    ]
