# Generated by Django 3.2.6 on 2024-04-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0034_alter_especificacion_des_esp'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='num_inf',
            field=models.IntegerField(null=True, verbose_name='Número de Informe'),
        ),
    ]
