# Generated by Django 3.2.6 on 2024-04-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0035_configuracion_num_inf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresoconciliacion',
            options={'ordering': ['id'], 'verbose_name': 'IngresoConciliacion', 'verbose_name_plural': 'IngresosConciliaciones'},
        ),
    ]
