# Generated by Django 3.2.6 on 2024-05-31 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0036_alter_ingresoconciliacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_pe', models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Configuracion')),
                ('num_exp', models.IntegerField(blank=True, null=True, verbose_name='Número de Expediente')),
                ('num_act', models.IntegerField(blank=True, null=True, verbose_name='Número de Acta')),
                ('num_inf', models.IntegerField(blank=True, null=True, verbose_name='Número de Informe')),
                ('est_pe', models.CharField(blank=True, choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=10, null=True, verbose_name='Estado Periodo')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'JJ_PERIODO',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='id_conf',
        ),
        migrations.DeleteModel(
            name='Configuracion',
        ),
        migrations.AddField(
            model_name='expediente',
            name='id_pe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ccjj.periodo', verbose_name='Id Periodo'),
        ),
    ]
