# Generated by Django 3.2.6 on 2024-05-31 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0037_auto_20240531_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_cat',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idcaj_con',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
