# Generated by Django 3.2.6 on 2024-06-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccjj', '0038_auto_20240531_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constanciasolicitante',
            name='id_sol',
        ),
        migrations.AlterField(
            model_name='cajaconciliacion',
            name='egre_con',
            field=models.FloatField(verbose_name='Egreso'),
        ),
        migrations.AlterField(
            model_name='cajaconciliacion',
            name='ing_con',
            field=models.FloatField(verbose_name='Ingreso Conciliacion'),
        ),
        migrations.AlterField(
            model_name='cajaconciliacion',
            name='ingcop_con',
            field=models.FloatField(verbose_name='Ingreso Copias Conciliacion'),
        ),
        migrations.AlterField(
            model_name='cajaconciliacion',
            name='toting_con',
            field=models.FloatField(verbose_name='Total Ingreso'),
        ),
        migrations.AlterField(
            model_name='conciliador',
            name='fec_doc',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Documento'),
        ),
        migrations.AlterField(
            model_name='conciliador',
            name='hor_doc',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Documento'),
        ),
        migrations.AlterField(
            model_name='egresodetalle',
            name='fecegredet_con',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Egreso Conciliacion Detalle'),
        ),
        migrations.AlterField(
            model_name='egresodetalle',
            name='horegredet_con',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Egreso Conciliacion Detalle'),
        ),
        migrations.AlterField(
            model_name='egresodetalle',
            name='monegre_det',
            field=models.FloatField(verbose_name='Monto Egreso'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fec_inf',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Informe'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='hor_inf',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Informe'),
        ),
        migrations.AlterField(
            model_name='ingresoconciliacion',
            name='pacpag_con',
            field=models.FloatField(verbose_name='Pago Pactado Conciliacion'),
        ),
        migrations.AlterField(
            model_name='ingresoconciliacion',
            name='pagpacade_con',
            field=models.FloatField(verbose_name='Pago Pactado Adelantado Conciliacion'),
        ),
        migrations.AlterField(
            model_name='ingresoconciliaciondetalle',
            name='fecingdet_con',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso Conciliacion Detalle'),
        ),
        migrations.AlterField(
            model_name='ingresoconciliaciondetalle',
            name='horingdet_con',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Ingreso Conciliacion Detalle'),
        ),
        migrations.AlterField(
            model_name='ingresoconciliaciondetalle',
            name='monadedet_con',
            field=models.FloatField(verbose_name='Monto Adelantado Detalle Conciliacion'),
        ),
        migrations.AlterField(
            model_name='ingresocopias',
            name='fec_cop',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Copias'),
        ),
        migrations.AlterField(
            model_name='ingresocopias',
            name='hor_cop',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Copias'),
        ),
        migrations.AlterField(
            model_name='ingresocopias',
            name='monpag_cop',
            field=models.FloatField(verbose_name='Monto Pago Copias'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='est_pe',
            field=models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', max_length=10, verbose_name='Estado Periodo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecdoc_sol',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hecdoc_sol',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Hechos de Solicitud'),
        ),
        migrations.DeleteModel(
            name='ConstanciaInvitado',
        ),
        migrations.DeleteModel(
            name='ConstanciaSolicitante',
        ),
    ]
