# Generated by Django 3.2.6 on 2023-09-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dni',
            new_name='dni_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='especialidad',
            new_name='esp_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='img_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='regfamilia',
            new_name='rgf_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reggeneral',
            new_name='rgg_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='tke_user',
        ),
        migrations.AddField(
            model_name='user',
            name='gen_user',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=10, verbose_name='Genero'),
        ),
    ]
