# Generated by Django 3.2.6 on 2023-10-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230921_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni_user',
            field=models.CharField(max_length=8, unique=True, verbose_name='DNI'),
        ),
    ]
